services:
  master:
    build:
      context: ./master
    container_name: master
    depends_on:
      - http_server
      - ftp_server
    networks:
      - fuzzing_net
    volumes:
      - ./master/logs:/shared/logs  # Mount shared logs directory
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket for Docker API access

  http_server:
    build:
      context: ./http_server
    container_name: http_server
    networks:
      - fuzzing_net
    volumes:
      - ./http_server/nginx.conf:/etc/nginx/nginx.conf  # Mount NGINX config file

networks:
  fuzzing_net:
    driver: bridge
