services:
  master:
    build:
      context: ./master
    container_name: master
    depends_on:
      - http_server
    networks:
      - fuzzing_net
    volumes:
      - ./master/logs:/shared/logs
      - /var/run/docker.sock:/var/run/docker.sock

  http_server:
    build:
      context: ./http_server
    container_name: http_server
    networks:
      - fuzzing_net
    volumes:
      - ./http_server/vuln_http_server.c:/usr/src/app/vuln_http_server.c  # Mount the C source file
    ports:
      - "8080:8080"  # Expose the HTTP server's port (if required for testing)

networks:
  fuzzing_net:
    driver: bridge